[tox]
envlist = pre-commit, pylint, pydocstyle, mypy, py36, py37, py38, jupyter, coverage
skip_missing_interpreters = true

[testenv]
extras = tests
commands =
    pytest

[testenv:coverage]
extras = tests
commands_pre = pip install -e {toxinidir}
commands =
    pytest --cov --cov-report xml:{toxinidir}/coverage-reports/coverage-all.xml

[testenv:pylint]
extras = develop
commands =
    pylint src/ tests/ setup.py

[testenv:pydocstyle]
deps = pydocstyle
commands =
    pydocstyle src/ tests/ setup.py
skip_install = true

[testenv:jupyter]
deps = jupyter
       nbconvert
       nbstripout
whitelist_externals=sh
commands_pre = sh -c "nbstripout jupyter-notebooks/*.ipynb"
commands = jupyter nbconvert --execute --to notebook jupyter-notebooks/*.ipynb
commands_post = sh -c "rm jupyter-notebooks/*.nbconvert.ipynb"

[testenv:pre-commit]
deps = pre-commit
skip_install = true
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:mypy]
extras = develop
setenv =
    MYPYPATH = src
commands = mypy src/ tests/

[pydocstyle]
convention = numpy
# D105 Missing docstring in magic method
# D202 No blank lines allowed after function docstring
add_ignore = D105, D202

[flake8]
# Specify the line length to be compatible with black.
max_line_length = 88
# Ignore inconsistent warnings:
# E203 whitespace before ':'
# W503 line break before binary operator
ignore = E203, W503
# Select all pycodestyle errors (E) and warnings (W) and pyflakes (F) errors.
select = E,F,W
